dataset: dlbcl
data_root: ""
split_dir: data/splits/

model: efficientnet_b2
pretrained: true
num_classes: 2

batch_size: 16
lr: 1.0e-4
weight_decay: 1.0e-5
epochs: 3
amp: true
num_workers: 0

patient_balanced_sampling: true
patient_aggregation: topk_mean
patient_top_k: 10
patient_percentile: 95.0
checkpoint_name: debug_dlbcl_topk_patient.pth

wandb:
  project: cancer-histo-dlbcl
  entity: YOUR_WANDB_ENTITY
